USE WAREHOUSE Assessment_I;
USE DATABASE HEVO_DB;
USE SCHEMA PUBLIC;


SELECT 'customers_raw' AS table_name, COUNT(*) AS cnt FROM HEVO_DB.PUBLIC.CUSTOMERS
UNION ALL
SELECT 'customers_transformed' AS table_name, COUNT(*) FROM HEVO_DB.PUBLIC.TRANSFORMED_CUSTOMERS
UNION ALL
SELECT 'orders' AS table_name, COUNT(*) FROM HEVO_DB.PUBLIC.ORDERS
UNION ALL
SELECT 'order_events' AS table_name, COUNT(*) FROM HEVO_DB.PUBLIC.ORDER_EVENTS
UNION ALL
SELECT 'feedback' AS table_name, COUNT(*) FROM HEVO_DB.PUBLIC.FEEDBACK;



SELECT * FROM HEVO_DB.PUBLIC.TRANSFORMED_CUSTOMERS LIMIT 10;
SELECT * FROM HEVO_DB.PUBLIC.ORDER_EVENTS LIMIT 10;

